export type ColorType = 'primary' | 'secondary' | 'danger' | 'success'
export type VariantType = 'contained' | 'outlined'
export type SizeType = 'small' | 'medium' | 'large'
export type PositionType = 'start' | 'center' | 'end'
export type StatusType = 'loading' | 'disabled' | 'error'
